services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - MODE=production
    restart: unless-stopped
    networks:
      - demo-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGODB_CONNECTIONSTRING=${MONGODB_CONNECTIONSTRING}
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - demo-network
  
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_DATABASE: todoX
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d:ro
    networks:
      - demo-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'    # HTTP
      - '81:81'    # Admin UI
      - '443:443'  # HTTPS
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge

volumes:
  mongodb-data: